### ISSUE TITLE
Create tests with Jest

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/bookeep#4]
# :rocket: Feature

This app doesn't have tests to assert that everything is working how it should work. Jest is already installed, because this react app was created with CRA.

**Comment by ryguigas0** [comment]
I'm new to react, but I want to help! So what does jest need to test and what does CRA means?

**Comment by juanbelieni** [comment]
Sure! For now, i think the simplest file to test is `bookApi.ts` (inside `src/services`), because the test will just have to assert if the data is being returned in the correct format.
And CRA means create-react-app :wink:

**Comment by ryguigas0** [comment]
Thanks! I'll get right on it!

**Comment by juanbelieni** [comment]
Ok, I will assign you to this issue. Thanks!

**Comment by ryguigas0** [comment]
Hey what more files need testing? So I can plan towards how long this will take. I'm quite new to react and testing with jest, so it might need some more time.

**Comment by juanbelieni** [comment]
The `.tsx` files need some tests too, but it would be better to start it later, because the repo has another pull request that are changing some components and pages. If you think that it's good, PR your branch with the test you already made.

**Comment by juanbelieni** [comment]
Thank you!
