### ISSUE TITLE
Create page to show more information of the book

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/bookeep#5]
# :rocket: Feature

The app only show books as a list, and it would be nice if the user could be redirected to a page with more information of the book.
It doesn't need to be a beautiful page, it only needs to work.

**Comment by gabLaroche** [comment]
I would like to work on this issue

**Comment by juanbelieni** [comment]
> I would like to work on this issue

Sure, I will assign you to this issue. Any doubts just ask here!

**Comment by gabLaroche** [comment]
I was wondering what additional information should we show on the book detail page?

**Comment by juanbelieni** [comment]
It can be:
 - ISBN
 - Publisher
 - Date of publishing

What do you think?

**Comment by gabLaroche** [comment]
Sounds good!

**Comment by juanbelieni** [comment]
#6 merged, thank you @gabLaroche!
