### ISSUE TITLE
[Feature Request] Add Focus to Search Bar when clicking the search link

### ISSUE THREAD

**Issue by gabLaroche** [juanbelieni/bookeep#7]
I think it would improve the user experience if the focus was in the search bar when clicking the search link

**Comment by juanbelieni** [comment]
I agree with you, and I think that it is not so difficult to implement this. Would you like to implement this feature?

**Comment by gabLaroche** [comment]
Yes I would like to implement this, indeed it's not so difficult to implement this.

**Comment by gabLaroche** [comment]
I created the pull request #9

**Comment by juanbelieni** [comment]
I already merged, thank you again!
